### ISSUE TITLE
optical data real time drive motionbuilder model

### ISSUE THREAD

**Issue by liyuebit** [Neill3d/MoPlugs#1]
Hello,
I can get 3D positioin of markers binded on actor, just like Optitrack MoCap system. How can I use these datas to drive a model in motionbuilder in real time? Most importantly, in real time.    Can you give me some suggestions？ 

Looking forward to your reply.
Thank you very much.

**Comment by Neill3d** [comment]
Hello, I guess you are asking about character retargeting. There is a lot of material avaliable on internet about that, just type "motionbuilder character retargeting" on a google search.
 And retargeting is working in run-time, so you can preview your marker data on a character straight away.

**Comment by liyuebit** [comment]
OK, I will have a try. Thank you.
